### ISSUE TITLE
How is "Throttled" handled?

### ISSUE THREAD

**Issue by jwoody02** [Shopify/checkout-kit-swift#44]
One big issue with the `checkoutCreate` mutation that I've encountered is `Throttled` error when there is over 4000 checkouts in under a minute, which is a common occurrence during flash sales. 

1) Does anyone know if the `cartCreate` mutation is restricted by this same limitation? 
2) If it is, will it still pass back a cart URL just fine or will it return something similar to the checkout create error?
2a) When we present the `CheckoutViewController` with this new mobile checkout, will the user be put in the "queue" that desktop/site users go thru when there are lots of checkouts?

Thanks

**Comment by kiftio** [comment]
Hi @jwoody02, apologies for the slow response. 

The `cartCreate` mutation isn't throttled in the same way as `checkoutCreate` and will continue to return a checkout URL under flash-sale like load. When users open that checkout URL, they will be put in the same queue as seen on desktop yes.

Hope that helps
