### ISSUE TITLE
Feature request: expose `modalPresentationStyle` or `isModalInPresentation`

### ISSUE THREAD

**Issue by tsopin** [Shopify/checkout-kit-swift#55]
In the checkout process, the package currently uses the `present` ViewController method, which presents the checkout as a card by default. 
However, this card-style presentation allows users to swipe it down during checkout easily and interrupt the checkout. 

It would be highly beneficial if we could have control over the `modalPresentationStyle` and the `isModalInPresentation` properties to either display it in full-screen mode or prevent it from being dismissed by swiping.

**Comment by cianBuckley** [comment]
Hi there! Thanks for taking the time to open a feature request. We will note this internally and track all feature requests which we will then take into consideration during planning. That said, a full-screen mode is not something we have on the roadmap as of today.

**Comment by tsopin** [comment]
Thank you for your response!

Just to clarify, setting the [`isModalPresentation`](https://developer.apple.com/documentation/uikit/uiviewcontroller/3229894-ismodalinpresentation) boolean to `true` will not change the modal presentation to full-screen. Instead, it will still use the card modal presentation with a close button in the corner but will disable the swipe-down gesture used for dismissing the modal.

**Comment by tsopin** [comment]
The feature was implemented in the latest release, version `0.8.0`, through the public exposure of the `CheckoutViewController`.
