### ISSUE TITLE
Presenting in SwiftUI

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Shopify/checkout-kit-swift#61]
Hi, I'm trying to use this SDK in a SwiftUi app. Since this view appears to be a UIKit one, I wrapped in it a `UIViewControllerRepresentable` to be used in Swiftui.

```swift
struct CheckoutView: UIViewControllerRepresentable {
    let url: URL
    
    func makeCoordinator() -> Coordinator {
        return Coordinator(self)
    }
    
    func makeUIViewController(context: Context) -> UIViewController {
        let viewController = UIViewController()
        return viewController
    }
    
    func updateUIViewController(_ viewController: UIViewController, context: Context) {
        ShopifyCheckout.present(checkout: url, from: viewController, delegate: context.coordinator)
    }
    
    class Coordinator: NSObject, CheckoutDelegate {
        var parent: CheckoutView
        
        init(_ checkoutView: CheckoutView) {
            parent = checkoutView
        }
        
        func checkoutDidFail(error: CheckoutError) {
        }
        
        func checkoutDidComplete() {
        }
        
        func checkoutDidCancel() {
        }
    }
}
```

However when I try to present this view as a modal sheet like below,

```swift
VStack {
// ...
}
.sheet(isPresented: $cartViewModel.isShowingCheckoutView) {
    CheckoutView(url: cartViewModel.cart!.checkoutURL)
}
```

I get the following error.

> Attempt to present <UINavigationController: 0x10513ae00> on <UIViewController: 0x104e0b860> (from <UIViewController: 0x104e0b860>) whose view is not in the window hierarchy.

Not sure what might be the issue. An example on how to use this SDK in SwiftUI in the docs would be nice.

Thank you!

---

**Update 1**

I looked at how view controllers are displayed in SwiftUI. This [example](https://swiftuirecipes.com/blog/send-mail-in-swiftui) shows how it's done for `MFMailComposeViewController`. As you can see, the view controller is configured in the `makeUIViewController()` method and SwiftUI automatically handles the presenting part.

I think the current way of showing the checkout view controller might have to be re-written to support both UIKit and SwiftUI. Maybe exposing the internal `CheckoutViewController`?

**Comment by cianBuckley** [comment]
Hi there! There has been a few requests for SwiftUI already and it is on our radar and I suspect the work for this will be completed quite soon. If a rewrite of the view controller is required then we will do that :)

**Comment by Isuru-Nanayakkara** [comment]
Sweet! Thank you 🙏
