### ISSUE TITLE
Bug Report: Dark Mode View Controller

### ISSUE THREAD

**Issue by tsopin** [Shopify/checkout-kit-swift#66]
The color scheme of the modal ViewController is based on system settings, instead of the theme passed to `ShopifyCheckoutKit.configuration.colorScheme`. 
The `light` checkout can be presented in a `dark` ViewController.

![IMG_0016](https://github.com/Shopify/checkout-kit-swift/assets/31713024/9b789427-1672-45ed-b4e8-5432d319db96)

**Comment by tsopin** [comment]
Thank you for the reply!

I need the header to align with the value set in the configuration. 

In this instance, while iOS was set to `dark mode`, my app was set to `light mode`, which was passed to the `ShopifyCheckoutKit.configuration.colorScheme`. 

The checkout content adhered to the `.light` setting, but the view controller and its header conformed to the system's `dark mode` setting.

No, I haven't used `automatic` since my app overrides the system's settings.

**Comment by markmur** [comment]
The [backgroundColor](https://github.com/Shopify/checkout-kit-swift#backgroundcolor) configuration should help with this. It will set the background color of the webview - which will also apply to the header. So if you set it to white for example, the whole sheet will be white when loading, and the header should remain white when finished loading.

Let me know if this works for you. Note that you may also need to modify the system text color to correct the text color of "checkout" in the header.
